openapi: 3.0.0
info:
  title: MeteoAPI
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
paths:
  /measurements:
    get:
      description: List svih merenja na datoj lokaciji
      operationId: api.getMeasurements
      parameters:
        - in: query
          name: location
          description: Naziv mesta/grada za kojeg želimo preuzmemo merenja.
          schema:
            type: string
            example: Kopaonik
          required: true
      responses:
        '200':
          description: Lista svih merenja na datoj lokaciji
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: "#/components/schemas/Measurement"
    post:
      operationId: api.createMeasurement
      description: Kreiranje merenja u datom vremenu, na datoj lokaciji, na datoj meteorološkoj stanici, za datu meteorološku promenljivu
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                time:
                  description: Vreme merenja
                  type: string
                  format: date-time
                  example: 2024-05-15T14:10:28Z
                variable:
                  description: Naziv meteorološke promenljive
                  type: object
                  example: {name: Vazdušni pritisak,
                           unit: hPa }
                value:
                  description: Vrednost meteorološke promenljive
                  type: number
                  format: float
                  example:  827.7
                source:
                  description: Izvora podataka
                  type: object
                  example: {code: PS1,
                            name: Planinska stanica 1,
                            location: {"name": "Kopaonik",
                                        "lat": 43.28504518887785,
                                        "long": 20.80100960793842,
                                        "country": "Srbija",
                                        "type": "Planina",
                                        "elevation": 1070},
                            description: Osnovni planinski meteorološki izvor}
                location:
                  description: Naziv lokacije
                  type: object
                  example: {name: Kopaonik,
                    lat: 43.28504518887785,
                    long: 20.80100960793842,
                    country: Srbija,
                    type: Planina,
                    elevation: 1070}
                measurement_sources:
                  description:  izvor merenja
                  type: object
                  example: {name: satelit,
                            lat: 0.0,
                            long: 0.0,
                            type: satelit}
              required:
                - time
                - variable
                - value 
                - source
                - location
                - measurement_sources
              example:
                    time: 2024-05-15T14:10:28Z
                    variable: {name: Vazdušni pritisak,
                               unit: hPa }
                    value: 827.7
                    source: {code: PS1,
                            name: Planinska stanica 1,
                            location: {"name": "Kopaonik",
                                        "lat": 43.28504518887785,
                                        "long": 20.80100960793842,
                                        "country": "Srbija",
                                        "type": "Planina",
                                        "elevation": 1070},
                            description: Osnovni planinski meteorološki izvor}
                    location: {name: Kopaonik,
                                lat: 43.28504518887785,
                                long: 20.80100960793842,
                                country: Srbija,
                                type: Planina,
                                elevation: 1070}
                    measurement_sources: {name: satelit,
                                          lat: 0.0,
                                          long: 0.0,
                                          type: satelit}
      responses:
        '201':
          description: Uspešno je kreirano merenje
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Measurement"
  /measurements/{id}:
    get:
      description: Vraća listu koja sadrži jedno merenje sa datim `id`-om
      operationId: api.getMeasurementById
      parameters:
        - in: path
          name: id
          description: Identifikator merenja (interni podatak)
          schema:
            type: integer
            example: 1
          required: true
      responses:
        '200':
          description: Uspešno vraćeno merenje
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Measurement"
    patch:
      description: Ažurira merenje sa datim `id`-om
      operationId: api.updateMeasurementById
      parameters:
        - in: path
          name: id
          description: Identifikator merenja (interni podatak)
          schema:
            type: integer
            example: 1
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                time:
                  description: Vreme merenja
                  type: string
                  format: date-time
                  example: 2024-05-15T15:02:10Z
                variable:
                  description: Naziv meteorološke promenljive
                  type: object
                  example: {name: Vazdušni pritisak,
                            unit: hPa }
                value:
                  description: Vrednost meteorološke promenljive
                  type: number
                  format: float
                  example: 825.7
                source:
                  description: Izvora podataka
                  type: object
                  example: {code: GS1,
                            name: Gradska stanica 1,
                            location: {"name": "Beogad",
                                        "lat": 43.28504518887785,
                                        "long": 20.80100960793842,
                                        "country": "Srbija",
                                        "type": "Grad",
                                        "elevation": 110},
                            description: Osnovni gradski meteorološki izvor}
                location:
                  description: Naziv lokacije
                  type: object
                  example: {name: Beograd,
                    lat: 43.28504518887785,
                    long: 20.80100960793842,
                    country: Srbija,
                    type: Grad,
                    elevation: 110}
                measurement_sources:
                  description:  izvora merenja
                  type: object
                  example: {name: automatska meteorološka stanica,
                                          lat: 43.4522346543,
                                          long: 21.23143654,
                                          type: meteorološka stancica}                      
      responses:
        '200':
          description: Merenje je uspešno ažurirano.
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Measurement"
    delete:
      description: Briše merenje čiji je identifikator `id`
      operationId: api.removeMeasurementById
      parameters:
        - in: path
          name: id
          description: Identifikator merenja (interni podatak)
          schema:
            type: integer
            example: 1
          required: true
      responses:
        '200':
          description: Nema sadržaja
  /locations:
    get:
      description: Vraća listu lokacija
      operationId: api.getLocations
      parameters:
        - in: query
          name: name
          description: Naziv lokacije na kojoj vrsimo merenja.
          schema:
            type: string
            enum:
             - Beograd
             - Dunav
             - Niš
             - Ribari 
             - Palić
             - Kopaonik
             - Zlatibor
          required: true
      responses:
        "200":
          description: Lista svih lokacija
          content:
            application/json:
              schema:
                schema:
                type: object
                $ref: "#/components/schemas/Location"
    post:
      operationId: api.createLocation
      description: Kreiranje nove lokacije
      requestBody:
        content:
          application/json:
            schema:
              type:
                object
              properties:
                name:
                    enum:
                    - Beograd
                    - Dunav
                    - Niš
                    - Ribari 
                    - Palić
                    - Kopaonik
                    - Zlatibor
                lat:
                  description: Geografska širina
                  type: number
                  example: 43.28504518887785
                long:
                  description: Geografska dužina
                  type: number
                  example: 20.80100960793842
                country:
                  description: Država lokacije
                  type: string
                  example: Srbija
                type:
                  description: Vrsta lokacije
                  type: string
                  example: Planina
                elevation:
                  description: Nadmorska visina
                  type: integer
                  example: 1070
              required:
                - name
                - lat
                - long
                - country
                - type
                - elevation
              example:
                name: Kopaonik
                lat: 43.28504518887785
                long: 20.80100960793842
                country: Srbija
                type: Planina
                elevation: 1070

      responses:
        '201':
          description: Lokacija uspešno kreirana
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Location"
  /locations/{id}:
    get:
      description: Vraća lokaciju sa datim `id`-om
      operationId: api.getLocationById
      parameters:
        - in: path
          name: id
          description: Identifikator lokacije (interni podatak)
          schema:
            type: integer
            example: 1
          required: true
      responses:
        '200':
          description: Uspešno vraćena lokacija
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Location"
    patch:
      description: Ažurira lokaciju sa datim `id`-om
      operationId: api.updateLocationById
      parameters:
        - in: path
          name: id
          description: Identifikator lokacije (interni podatak)
          schema:
            type: integer
            example: 1
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  enum:
                    - Beograd
                    - Dunav
                    - Niš
                    - Ribari 
                    - Palić
                    - Kopaonik
                    - Zlatibor
                lat:
                  description: Geografska širina
                  type: number
                  example: 46.098042855368334
                long:
                  description: Geografska dužina
                  type: number
                  example: 19.7679819
                country:
                  description: Država lokacije
                  type: string
                  example: Srbija
                type:
                  description: Vrsta lokacije
                  type: string
                  example: Jezero
                elevation:
                  description: Nadmorska visina
                  type: integer
                  example: 100
              required:
                - name
                - lat
                - long
                - country
                - type
                - elevation
              example:
                name: Palić
                lat: 46.098042855368334
                long: 19.7679819
                country: Srbija
                type: jezero
                elevation: 100

      responses:
        '200':
          description: Lokacija uspešno ažurirana
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Location"  
    delete:
      description: Briše lokaciju čiji je identifikator `id`
      operationId: api.removeLocationById
      parameters:
        - in: path
          name: id
          description: Identifikator lokacije (interni podatak)
          schema:
            type: integer
            example: 1
          required: true
      responses:
        '200':
          description: Nema sadržaja
  /variables:
    get:
      description: Vraća listu svih meteoroloških promenljivih
      operationId: api.getVariables
      parameters:
        - in: query
          name: name
          description: Naziv varijable koju zelimo da merimo
          schema:
            type: string
            enum:
             - Vazdušni pritisak
             - Temperatura
             - Padavine
             - UV index
             - Brzina vetra
          required: true
      responses:
        '200':
          description: Lista svih promenljivih
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: "#/components/schemas/Variable"
    post:
      operationId: api.createVariable
      description: Kreiranje nove meteorološke promenljive
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  description: Naziv promenljive
                  type: string
                  enum:
                    - Vazdušni pritisak
                    - Temperatura
                    - Padavine
                    - UV index
                    - Brzina vetra
                unit:
                  description: Jedinica promenljive
                  type: string
                  example: hPa
              required:
                - name
                - unit
              example:
                name: Vazdušni pritisak
                unit: hPa
      responses:
        '201':
          description: Promenljiva uspešno kreirana
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Variable"
  /variables/{id}:
    get:
      description: Vraća promenljivu sa datim `id`-om
      operationId: api.getVariableById
      parameters:
        - in: path
          name: id
          description: Identifikator promenljive (interni podatak)
          schema:
            type: integer
            example: 1
          required: true
      responses:
        '200':
          description: Uspešno vraćena promenljiva
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Variable"
    patch:
      description: Ažurira promenljivu sa datim `id`-om
      operationId: api.updateVariableById
      parameters:
        - in: path
          name: id
          description: Identifikator promenljive (interni podatak)
          schema:
            type: integer
            example: 1
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  description: Naziv promenljive
                  type: string
                  enum:
                    - Vazdušni pritisak
                    - Temperatura
                    - Padavine
                    - UV index
                    - Brzina vetra
                unit:
                  description: Jedinica promenljive
                  type: string
                  example: celzijus
              required:
                - name
                - unit
              example:
                name: Temperatura
                unit: celzijus
      responses:
        '200':
          description: Promenljiva uspešno ažurirana
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Variable"
    delete:
      description: Briše promenljivu čiji je identifikator `id`
      operationId: api.removeVariableById
      parameters:
        - in: path
          name: id
          description: Identifikator promenljive (interni podatak)
          schema:
            type: integer
            example: 1
          required: true
      responses:
        '200':
          description: Nema sadržaja
  /sources:
    get:
      description: Vraća listu svih izvora podataka 
      operationId: api.getSource
      parameters:
        - in: query
          name: code
          description: Kod izvora podataka sa kojih preuzmemo merenja.
          schema:
            type: string
            enum:
               - GS1
               - RS1
               - PS1
               - JS1
               - SS1
          required: true
      responses:
        '200':
          description: Lista svih izvora merenja
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: "#/components/schemas/Source"
    post:
      operationId: api.createSource
      description: Kreiranje novog izvora merenja
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  description: Kod (skraćeni naziv)
                  type: string
                  enum:
                    - GS1
                    - RS1
                    - PS1
                    - JS1
                    - SS1
                name:
                  description: Naziv izvora
                  type: string 
                  example: Planinska stanica 1
                location:
                  description: Informacije o lokaciji
                  type: object
                  example: {"name": "Kopaonik",
                    "lat": 43.28504518887785,
                    "long": 20.80100960793842,
                    "country": "Srbija",
                    "type": "Planina",
                    "elevation": 1070}
                description:
                  description: Opis izvora
                  type: string
                  example: Glavna planinska stanica 
              required:
                - code
                - name
                - location
                - description
              example:
                code: PS1
                name: Planinska stanica 1
                location: {"name": "Kopaonik",
                    "lat": 43.28504518887785,
                    "long": 20.80100960793842,
                    "country": "Srbija",
                    "type": "Planina",
                    "elevation": 1070}
                description: Glavna meteorološka planinska stanica 
      responses:
        '201':
          description: Izvor merenja uspešno kreiran
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Source"
  /sources/{id}:
    get:
      description: Vraća izvor merenja sa datim `id`-om
      operationId: api.getSourceById
      parameters:
        - in: path
          name: id
          description: Identifikator izvora merenja (interni podatak)
          schema:
            type: integer
            example: 1
          required: true
      responses:
        '200':
          description: Uspešno vraćen izvor merenja
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Source"
    patch:
      description: Ažurira izvor merenja sa datim `id`-om
      operationId: api.updateSourceById
      parameters:
        - in: path
          name: id
          description: Identifikator izvora merenja (interni podatak)
          schema:
            type: integer
            example: 1
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  description: Kod (skraćeni naziv)
                  type: string
                  enum:
                    - GS1
                    - RS1
                    - PS1
                    - JS1
                    - SS1
                name:
                  description: Naziv izvora
                  type: string 
                  example: Vazdušna stanica 1
                location:
                  description: Informacije o lokaciji 
                  type: object
                  example: {"name": "Kopaonik",
                    "lat": 43.28504518887785,
                    "long": 20.80100960793842,
                    "country": "Srbija",
                    "type": "Planina",
                    "elevation": 1070}
                description:
                  description: Opis izvora
                  type: string
                  example: Vazdušna stanica Niša
              required:
                - code
                - name
                - location
                - description
              example:
                code: PS1
                name: Planinska stanica 1
                location: {"name": "Kopaonik",
                    "lat": 43.28504518887785,
                    "long": 20.80100960793842,
                    "country": "Srbija",
                    "type": "Planina",
                    "elevation": 1070}
                description: Vazdušna stancica Kopaonika
      responses:
        '200':
          description: Izvor merenja uspešno ažuriran
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Source"
    delete:
      description: Briše izvor merenja čiji je identifikator `id`
      operationId: api.removeSourceById
      parameters:
        - in: path
          name: id
          description: Identifikator izvora merenja (interni podatak)
          schema:
            type: integer
            example: 1
          required: true
      responses:
        '200':
          description: Nema sadržaja
  /stations:
    get:
      description: Vraća listu svih stanica za merenje
      operationId: api.getStation
      parameters:
        - in: query
          name: type
          description: Tip stanice na kojoj su izvršena merenja
          schema:
            type: string
            enum:
              - automatska
              - ručna
              - hibridna
          required: true
      responses:
        '200':
          description: Lista svih stanica merenja
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: "#/components/schemas/Station"
    post:
      operationId: api.createStation
      description: Kreiranje nove stanice merenja
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  description: Naziv stanice merenja
                  type: string
                  example: Automatic Weather Station
                type:
                  enum:
                    - automatska
                    - ručna
                    - hibridna
                capacity:
                  description: Kapacitet stanice
                  type: integer
                  example: 100
                location:
                  description: Informacije o lokaciji
                  type: object
                  example: {"name": "Kopaonik",
                    "lat": 43.28504518887785,
                    "long": 20.80100960793842,
                    "country": "Srbija",
                    "type": "Planina",
                    "elevation": 1070}
              required:
                - name
                - type
                - capacity
                - location
              example:
               name: Meteorološka stanica Kopaonik
               type: automatska
               capacity: 100
               location: {"name": "Kopaonik",
                    "lat": 43.28504518887785,
                    "long": 20.80100960793842,
                    "country": "Srbija",
                    "type": "Planina",
                    "elevation": 1070}

      responses:
        '201':
          description: Stanica merenja uspešno kreirana
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Station"
  /stations/{id}:
    get:
      description: Vraća stanicu merenja sa datim `id`-om
      operationId: api.getStationById
      parameters:
        - in: path
          name: id
          description: Identifikator stanice merenja (interni podatak)
          schema:
            type: integer
            example: 1
          required: true
      responses:
        '200':
          description: Uspešno vraćena stanica merenja
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Station"
    patch:
      description: Ažurira stanicu merenja sa datim `id`-om
      operationId: api.updateStationById
      parameters:
        - in: path
          name: id
          description: Identifikator stanice merenja (interni podatak)
          schema:
            type: integer
            example: 1
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  description: Naziv stanice merenja
                  type: string
                  example: Meteorološka stanica Palić
                type:
                  enum:
                    - automatska
                    - ručna
                    - hibridna
                capacity:
                  description: Kapacitet stanice
                  type: integer
                  example: 10
                location:
                  description: Informacije o lokaciji
                  type: object
                  example: {"name": "Kopaonik",
                    "lat": 43.28504518887785,
                    "long": 20.80100960793842,
                    "country": "Srbija",
                    "type": "Planina",
                    "elevation": 1070}
              example:
                id: 2
                name: Meteorološka stanica Palić
                type: ručna
                capacity: 10
                location: {"name": "Kopaonik",
                    "lat": 43.28504518887785,
                    "long": 20.80100960793842,
                    "country": "Srbija",
                    "type": "Planina",
                    "elevation": 1070}

      responses:
        '200':
          description: Stanica merenja uspešno ažurirana
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Station"
    delete:
      description: Briše stanicu merenja čiji je identifikator `id`
      operationId: api.removeStationById
      parameters:
        - in: path
          name: id
          description: Identifikator stanice merenja (interni podatak)
          schema:
            type: integer
            example: 1
          required: true
      responses:
        '200':
          description: Nema sadržaja

  /measurement_sources:
    get:
      description: Vraća listu svih izvora merenja
      operationId: api.getMeasurementSources
      parameters:
        - in: query
          name: type 
          description: Tip izvora merenja (satelit, meteorološka stanica, senzor na terenu)
          schema:
            type: string
            enum:
              - satelit
              - meteorološka stanica
              - senzor na terenu
          required: true
      responses:
        '200':
          description: Lista svih izvora merenja
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: "#/components/schemas/MeasurementSource"
    post:
      operationId: api.createMeasurementSources
      description: Kreiranje nove stanice merenja
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  description: Naziv izvora merenja
                  type: string
                  example: Sentinel
                lat:
                  description: Geografska širina
                  type: number
                  example: 43.28504518887785
                long:
                  description: Geografska dužina
                  type: number
                  example: 20.80100960793842
                type:
                  description: Tip merenja
                  type: string
                  enum:
                    - satelit
                    - meteorološka stanica
                    - senzor na terenu
              required:
                - name
                - lat
                - long
                - type
              example:
                name: satelit
                lat: 0.0
                long: 0.0
                type: satelit
              $ref: "#/components/schemas/MeasurementSource"
      responses:
        '201':
          description: Uspešno kreiran novi izvor merenja
          content:
           application/json:
             schema:
               $ref: "#/components/schemas/MeasurementSource"

  /measurement_sources/{id}:
    get:
     description: Dobijanje izvora merenja po ID-ju
     operationId: api.getMeasurementSourceById
     parameters:
      - in: path
        name: id
        description: Identifikator izvora merenja (interni podatak)
        schema:
          type: integer
        required: true
     responses:
      '200':
        description: Uspešno dobijen izvor merenja
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MeasurementSource"
    patch:
      description: Ažuriranje izvora merenja po ID-ju
      operationId: api.updateMeasurementSourceById
      parameters:
        - in: path
          name: id
          description: Identifikator izvora merenja (interni podatak)
          schema:
           type: integer
           example: 1
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  description: Naziv izvora merenja
                  type: string
                  example: automatska meteorološka stanica
                lat:
                  description: Geografska širina
                  type: number
                  example: 43.28504518887785
                long:
                  description: Geografska dužina
                  type: number
                  example: 20.80100960793842
                type:
                  enum:
                    - satelit
                    - meteorološka stanica
                    - senzor na terenu
              example:
                  name: automatska meteorološka stanica
                  lat: 43.28504518887785
                  long: 20.8010096079384
                  type: meteorološka stanica
      responses:
        '200':
          description: Uspešno ažuriran izvor merenja
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MeasurementSource"
    delete:
      description: Brisanje izvora merenja po ID-ju
      operationId: api.removeMeasurementSourceById
      parameters:
        - in: path
          name: id
          description: Identifikator izvora merenja (interni podatak)
          schema:
            type: integer
            example: 1
          required: true
      responses:
        '200':
          description: Nema sadržaja



components:
  schemas:
    Measurement:
      type: object
      description: merenja
      x-tablename: measurement
      properties:
        id: 
          description: Identifikacioni broj
          type: integer
          x-primary-key: true
          x-autoincrement: true
          example: 1
        time:
          description: Vreme merenja
          type: string
          format: date-time
          example: 2024-05-15T14:10:28Z
        variable:
          description: Naziv meteorološke promenljive
          type: object
          $ref: "#/components/schemas/Variable"
        value:
          description: Vrednost meteorološke promenljive
          type: number
          format: float
          example: 827.7
        source:
          description: Izvora podataka
          type: object
          $ref: "#/components/schemas/Source"
        location:
          description: Naziv lokacije
          type: object
          $ref: "#/components/schemas/Location"
        measurement_sources:
          description: Izvor merenja
          type: object
          $ref: "#/components/schemas/MeasurementSource"
      required:
          - time
          - variable
          - value 
          - source
          - location
          - measurement_sources
      example:
        time: 2024-05-15T14:10:28Z
        variable: {name: Vazdušni pritisak,
                   unit: hPa} 
        value: 827.7
        source: {code: PS1,
                            name: Planinska stanica 1,
                            location: {"name": "Kopaonik",
                                        "lat": 43.28504518887785,
                                        "long": 20.80100960793842,
                                        "country": "Srbija",
                                        "type": "Planina",
                                        "elevation": 1070},
                            description: Osnovni planinski meteorološki izvor}
        location: {name: Kopaonik,
                    lat: 43.28504518887785,
                    long: 20.80100960793842,
                    country: Srbija,
                    type: Planina,
                    elevation: 1070}
        measurement_sources: {name: satelit,
                              lat: 0.0,
                              long: 0.0,
                              type: satelit}
    Location:
      type: object
      description: lokacije
      x-tablename: location
      properties:
        id:
          description: Identifikacioni broj (interni ključ)
          type: integer
          x-primary-key: true
          x-autoincrement: true
          example: 1
        name:
          description: Naziv lokacije
          type: string
          enum:
             - Beograd
             - Dunav
             - Niš
             - Ribari 
             - Palić
             - Kopaonik
             - Zlatibor
        lat:
          description: Geografska širina
          type: number
          example: 43.28504518887785
        long:
          description: Geografska dužina
          type: number
          example: 20.80100960793842
        country:
          description: Država lokacije
          type: string
          enum:
             - Beograd
             - Dunav
             - Niš
             - Ribari 
             - Palić
             - Kopaonik
             - Zlatibor
        type:
         description: Vrsta lokacije
         type: string
         example: Planina
        elevation:
          description: Nadmorska visina
          type: integer
          example: 1070
      required:
         - name
         - lat
         - long
         - country
         - type
         - elevation
      example:
        name: Kopaonik
        lat: 43.28504518887785
        long: 20.80100960793842
        country: Srbija
        type: Planina
        elevation: 1070
    Variable:
      type: object
      description: Meteorološka promenljiva
      x-tablename: variable
      properties:
        id:
          description: Identifikacioni broj (interni ključ)
          type: integer
          x-primary-key: true
          x-autoincrement: true
        name:
          description: Naziv meteorološke varijable
          type: string
          enum:
          - Vazdušni pritisak
          - Temperatura
          - Padavine
          - UV index
          - Brzina vetra
        unit:
          description: Jedinica promenljive
          type: string
          example: hPa
      required:
        - name
        - unit
      example:
        name: Vazdušni pritisak
        unit: hPa    
    Source:
      type: object
      description: Naziv izvora podataka
      x-tablename: source
      properties:
        id:
          description: Identifikacioni broj (kluč)
          type: integer
          x-primary-key: true
          x-autoincrement: true
        code:
           description: Kod (skraćeni naziv)
           type: string
           enum:
              - GS1
              - RS1
              - PS1
              - JS1
              - SS1
        name:
          description: Naziv izvora podataka
          type: string
        location:
            description: Informacije o lokaciji
            type: object
            $ref: "#/components/schemas/Location"
        description:
            description: Opis izvora
            type: string
      required:
          - code
          - name
          - location
          - description
      example:
        code: PS1
        name: Planinska stanica 1
        location: {"name": "Kopaonik",
                    "lat": 43.28504518887785,
                    "long": 20.80100960793842,
                    "country": "Srbija",
                    "type": "Planina",
                    "elevation": 1070}
        description: Osnovni planinski meteorološki izvor
    Station:
      type: object
      description: Stanice za merenje
      x-tablename: station
      properties:
        id:
          description: Identifikacioni broj (interni ključ)
          type: integer
          x-primary-key: true
          x-autoincrement: true
          example: 1
        name:
          description: Naziv meteoroloških stanica
          type: string
          example: Meteorološka stanica Kopaonik
        type:
          description: Tip stanice
          type: string
          enum:
            - automatska
            - ručna
            - hibridna
        capacity:
          description: Kpacitet stanice
          type: integer
          example: 100
        location:
            description: Informacije o lokaciji
            type: object
            $ref: "#/components/schemas/Location"
      required:
        - name
        - type
        - capacity
        - location
      example:
          name: Meteorološka stanica Kopaonik
          type: automatska
          capacity: 100
          location: {"name": "Kopaonik",
                    "lat": 43.28504518887785,
                    "long": 20.80100960793842,
                    "country": "Srbija",
                    "type": "Planina",
                    "elevation": 1070}
    MeasurementSource:
      type: object
      description: Naziv izvora merenja
      x-tablename: measurementSource
      properties:
        id:
          description: Identifikacioni broj (kluč)
          type: integer
          x-primary-key: true
          x-autoincrement: true
        name:
          description: Naziv izvora merenja
          type: string
          example: automatska meteorološka stanica
        lat:
          description: Geografska širina
          type: number
          example: 43.28504518887785
        long:
          description: Geografska dužina
          type: number
          example: 20.80100960793842 
        type:
          description: Tip merenja
          type: string
          enum:
            - satelit
            - meteorološka stanica
            - senzori na terenu
      required:
        - name
        - lat
        - long
        - type
      example:
        name: satelit
        lat: 0.0
        long: 0.0
        type: satelit
    
  securitySchemes:
    UserToken:
      type: apiKey
      in: header
      name: Authorization

